---
pool: 
  name: "default"
  vmImage: ubuntu-20.04

trigger:
  - master

steps: 
  - task: Docker@2
    displayName: Build
    inputs: 
      command: build
      buildContext: .
      repository: 'StudentCourses'
      tags: '$(Build.BuildId)'     
